name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying to Google App Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn install

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud CLI
        run: |-
          gcloud config set account ${{ secrets.SERVICE_ACCOUNT }}
          gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Replace app.yml secrets
        uses: 73h/gae-app-yaml-replace-env-variables@v0.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          DB_USER: ${{ secrets.DB_USER}}
          DB_NAME: ${{ secrets.DB_NAME}}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
          DB_CONNECTION_NAME: ${{ secrets.DB_CONNECTION_NAME}}
        with:
          app_yaml_path: app.yaml

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: app.yaml